"""Writes the shared parts of every page: the main navigation (with its dropdown menus)
and the "Trusted by" client-logo row shown just above the footer.

Run from the repo root after changing the menu:  python3 tools/build_nav.py
The home page links to its own sections (#about); inner pages link to index.html#about.
"""
import re

SERVICES = [('design', 'New HVAC Plant'), ('upgrade', 'HVAC Plant Upgrade'), ('control', 'Automation &amp; Control Systems'),
            ('installation', 'Installation Support'), ('commissioning', 'Testing &amp; Commissioning')]
EQUIPMENT = [
    ('div-automation', 'Automation &amp; Controls', [('panels', 'Electric Panels'), ('inverters', 'Inverters &amp; Automation System'), ('components', 'Electrical Components'), ('sensors', 'Temperature &amp; Humidity Sensors')]),
    ('div-airhandling', 'Air Distribution', [('axial-fan', 'Axial Fan'), ('air-washer', 'Air Washer'), ('dampers', 'Air Control Dampers'), ('louvre', 'Rainproof Louvers')]),
    ('div-filtration', 'Filtration &amp; Dust Handling', [('rotary-filter', 'Rotary Air Filter System'), ('dust', 'Dust Collection System'), ('centrifugal-fan', 'Centrifugal Fan')]),
    ('div-fire', 'Fire Protection Systems', [('fire-protection', 'Spark, Metal &amp; Fire Protection'), ('mdx02', 'MDX02 Metal &amp; Spark Diverter'), ('asd119a3', 'ASD119A3 Spark Diverter'), ('xta3', 'XTA3 Multi-mixer Fire Protection')]),
]


# Client logos (files in assets/clients/). Add a line here and run this script.
LOGOS = [('nishat-chunian', 'Nishat Chunian Ltd'), ('naveena-denim', 'Naveena Denim Ltd'), ('din-industries', 'Din Industries'),
         ('fazal-cloth', 'Fazal Cloth Mills Ltd'), ('rafiq-jamil', 'Rafiq Jamil Textile Industries')]


def logo_marquee(indent='      '):
    row = lambda hidden: '\n'.join(
        f'{indent}      <li class="logo-tile"><img src="assets/clients/{f}.png" alt="{"" if hidden else n}" loading="lazy"></li>' for f, n in LOGOS)
    return f'''{indent}<div class="logo-marquee">
{indent}  <p class="logo-marquee-title">Trusted by leading mills in Pakistan</p>
{indent}  <div class="logo-track">
{indent}    <ul class="logo-row">
{row(False)}
{indent}    </ul>
{indent}    <ul class="logo-row" aria-hidden="true">
{row(True)}
{indent}    </ul>
{indent}  </div>
{indent}</div>'''


def logo_band():
    """Inner pages: its own band just above the footer."""
    return f'''<!-- logos:start (generated by tools/build_nav.py) -->
  <section class="logo-band" aria-label="Our clients">
    <div class="container">
{logo_marquee('      ')}
    </div>
  </section>
  <!-- logos:end -->'''


def logo_inline():
    """Home page: inside the Clients section, under the client tables."""
    return f'''<!-- logos:start (generated by tools/build_nav.py) -->
{logo_marquee('      ')}
      <!-- logos:end -->'''


def col(head_href, head, links):
    items = ''.join(f'\n              <a href="{h}">{t}</a>' for h, t in links)
    return f'''            <div class="dropdown-col">
              <a href="{head_href}" class="dropdown-head">{head}</a>{items}
            </div>'''


def dropdown(key, label, cols, ncols, sections=None):
    return f'''        <div class="dropdown" id="{key}Dropdown">
          <button class="nav-link dropdown-toggle" data-section="{sections or key}" aria-expanded="false" aria-controls="{key}Menu">
            {label} <span class="caret" aria-hidden="true"></span>
          </button>
          <div class="dropdown-menu cols-{ncols}" id="{key}Menu">
{chr(10).join(cols)}
          </div>
        </div>'''


def nav(p):  # p = '' on the home page, 'index.html' on inner pages
    svc = lambda s: f'service.html?s={s}'
    eq = lambda e: f'detail.html?eq={e}'
    services = dropdown('services', 'Services', [
        col(f'{p}#services', 'HVAC Solutions', [(svc(s), t) for s, t in SERVICES[:3]]),
        col(f'{p}#services', 'Project Delivery', [(svc(s), t) for s, t in SERVICES[3:]]),
    ], 2)
    equipment = dropdown('products', 'Products', [col(f'{p}#{a}', h, [(eq(e), t) for e, t in items]) for a, h, items in EQUIPMENT], 4)
    ind = lambda i: f'detail.html?ind={i}'
    company = dropdown('company', 'Company', [
        col(f'{p}#about', 'About AirKing', [(f'{p}#about', 'Who we are'), (f'{p}#history', 'Our history'), (f'{p}#factory', 'Inside AirKing (factory)'), (f'{p}#team', 'Meet our team')]),
        col(f'{p}#industries', 'Industries', [(ind('spinning'), 'Spinning'), (ind('weaving'), 'Weaving'), (ind('synthetic-fibre'), 'Synthetic Fibre'), (ind('knitting'), 'Knitted Fabric'), (ind('nonwoven'), 'Non-woven Fabric'), (ind('other'), 'Other Industries')]),
        col(f'{p}#clients', 'References', [(f'{p}#clients', 'Key customers'), (f'{p}#why', 'Why AirKing?')]),
    ], 3, sections='company about history factory industries clients team why')
    return f'''<nav class="nav" id="nav" aria-label="Main">
        <span class="nav-bubble" id="navBubble" aria-hidden="true"></span>
{company}
{services}
{equipment}
        <a href="#contact" class="nav-link">Contact Us</a>
      </nav>'''


for page, prefix in [('index.html', ''), ('service.html', 'index.html'), ('detail.html', 'index.html'), ('privacy.html', 'index.html')]:
    html = open(page, encoding='utf-8').read()
    html, n = re.subn(r'<nav class="nav" id="nav".*?</nav>', lambda m: nav(prefix), html, count=1, flags=re.S)
    assert n == 1, page
    # remove whatever logo row is there, then put it in the right place for this page
    html = re.sub(r'\n?[ ]*<!-- logos:start.*?<!-- logos:end -->\n?', '\n', html, count=1, flags=re.S)
    if page == 'index.html':
        clients = html.index('id="clients"')
        end = html.index('    </div>\n  </section>', clients)
        html = html[:end] + '      ' + logo_inline() + '\n' + html[end:]
    else:
        html = html.replace('  <!-- ===================== FOOTER ===================== -->', '  ' + logo_band() + '\n\n  <!-- ===================== FOOTER ===================== -->', 1)
    open(page, 'w', encoding='utf-8').write(html)
    print('nav updated:', page)
